### ISSUE TITLE
Help! Deployment always failed.

### ISSUE THREAD

**Issue by highcold** [Bitergia/fiware-devguide-app#121]
when I finished the command "docker-compose up -d", all the components started. However I can't visit "http://tourguide", and I use "docker-compose ps" to check state of all components. The result were "cygnus       /docker-entrypoint.sh         Exit 1"   and  "ul20client           /docker- entrypoint.sh--acpi         Exit 1"

**Comment by dmabtrg** [comment]
Hi, could you provide the following information, please?
- version of TourGuide (master, develop, release (e.g. 0.5.1))
- operating system
- output of the `docker-compose logs` command (create a gist/pastebin and put the url here, do not paste the output directly in the issue)

Also, make sure you have the latest images for the version you're using via `docker-compose pull`.

There's a pending PR (#118) that will replace our custom cygnus image with the official image and that should fix the cygnus container exiting.

The problem with ul20client, without seeing the logs is hard to guess.

Thank you.

**Comment by highcold** [comment]
Thank you for your answer in time, and I so sorry for my late reply due to some urgent things  to deal with and bad network environment to update components in China.
Using your method, I have solved the problem related to cygnus, but  another problem still exists.
Here is the information:
- version of TourGuide is **develop**
- OS is **ubuntu 14.04** 
- Although I have fix the hosts, I can't use gist to create a gist in China. Because the log is big(1.8M),  I upload  [screen.log](http://pan.baidu.com/s/1c1Y8mVu). If I find the way to create a gist, I will upload it in time.

Thank you again for your help @dmabtrg .

**Comment by dmabtrg** [comment]
The following is just a guess, but we've seen it before on some systems.

The `ul20client` container uses the acpi subsystem by default.  If the system where your're running the containers does not support it, it will fail.  Modify the `command` directive on the `docker-compose.yml` file for that container from:

```
command: --acpi
```

to:

```
command: --fake --min 0 --max 100 --variance 5
```

This will create a fake sensor instead of trying to use the ones available on the system, with a minimum value of 0, a maximum of 100 and varying +/-5 between each reading at random.

**Comment by highcold** [comment]
Thank you for your answer.
When I modified the docker-compose.yml, the result was still **Exit1**

```
ul20client:
    image: bitergia/ul20-client:latesct
    hostname: ul20client
    container_name: ul20client
    links:
        - orion
        - idas
    command: --fake --min 0 --max 100 -variance 5
    environment:
        - UL20_IOTA_HOST=idas
        - UL20_IOTA_PORT=7896
        - UL20_IOTA_ADMIN_PORT=4041
        - UL20_API_KEY=tourguide-devices
        - UL20_SERVICE_NAME=tourguide
```

I am expected to introduce more about what I am doing. I am doing this tourguide on Virtual Machine with Ubuntu 14.04, and it doesn't feed any sensor to this program nowadays. What I do is following the the tourguide introduction and I can't get guiding from surrounding people or Chinese documents. So I think I may do something wrong in this process and I don't know that.
If it works and we put it in practical projects, I think fiware will popularize to some extent in China.
Thank you for your help. @dmabtrg

**Comment by dmabtrg** [comment]
You are missing a `-` in `--variance`.  It should have two `-` instead of one.

If that doesn't solve it, try `docker logs ul20client | tail -n 20`.  That will show the last 20 lines of the log of that container and probably show the error.  Paste that lines here if it's still failing.

**Comment by highcold** [comment]
Adding a `-`, it still doesn't work.
The log is :

```
root@ubuntu:/home/tyrion/fiware# docker logs ul20client | tail -n 20
* Asking to http://idas:4041/iot/services
* Headers: {'Fiware-Service': 'tourguide', 'content-type': 'application/json', 'Fiware-ServicePath': '/', 'X-Auth-Token': 'NULL'}
* Sending PAYLOAD: 
{
    "services": [
        {
            "token": "token2", 
            "apikey": "tourguide-devices", 
            "resource": "/iot/d", 
            "entity_type": "thing", 
            "cbroker": "http://orion:1026"
        }
    ]
}

...

* Status Code: 409
* Response: 
{"name":"DUPLICATE_GROUP","message":"A device configuration already exists for resource /iot/d and API Key tourguide-devices"}
```

**Comment by dmabtrg** [comment]
Ok.  The first thing the container does is try to register the service with the IoT Agent (the idas container), and this is what it's failing now.  The message shows that the service already exists (and this will stop the container).  Could you try again by removing the old containers first?  Do:

```
docker-compose kill
```

to stop any container still running, then

```
docker-compose rm -fv
```

to remove the stopped containers.  After this, you can start a new set of containers with

```
docker-compose up -d
```

Please note that the ul20client container is a simple client for the IoT Agent and this functionality is now integrated in the main TourGuide application, so this container might be removed in the future.  If you're still having problems with this container, you can disable it completely by commenting the ul20client section in the docker-compose.yml file.

Hope that helps.

**Comment by highcold** [comment]
After doing what you tell me, using command `docker-compose ps` showed status of all components were up, but I can't still visit `http://tourguide`. 
I have run the `./get-docker-hosts`. 

```
root@ubuntu:/home/tyrion/fiware/docker/docker/utils# ./get-docker-hosts 
2016/08/10 18:49:09 +0800   OS: Linux
2016/08/10 18:49:09 +0800   Using hosts file '/etc/hosts'
### BEGIN Docker container IPs ###
172.17.0.10    tourguide tourguide
172.17.0.9    ul20client ul20client
172.17.0.8    cygnus compose_cygnus_1 cygnus cygnus_1
172.17.0.7    idas compose_idas_1 idas idas_1
172.17.0.5    orion compose_orion_1 orion orion_1
172.17.0.6    keyrock keyrock
172.17.0.4    authzforce authzforce
172.17.0.2    mongodb compose_mongodb_1 mongo mongodb mongodb_1
172.17.0.3    mysql mysql
### END Docker container IPs ###
```

Visiting `http://tourguide` still failed. 
Then I visit `172.17.0.10`, and the website directly go to ``172.17.0.10/client/` which shows a map and a button `log in`. However when I click this button, webpage showed `404 not found` and website was `tourguide/auth`. After doing this, I try to visit other ip(172.17.0.10-172.17.0.2), but all pages can't be visited.

Thank you for your patience and guiding. @dmabtrg

**Comment by dmabtrg** [comment]
You should pass the `-m` flag to `get-docker-hosts` to actually modify the `/etc/hosts` file.  If you don't, it will show what will be added, but will not modify the file.

**Comment by highcold** [comment]
Thank you. @dmabtrg
It works, and I will be more  careful what I do.

**Comment by dmabtrg** [comment]
Ok.  I'm closing the issue then.
